### ISSUE TITLE
I dont know how to download it

### ISSUE THREAD

**Issue by marius62810** [fotvnetwork/iptv-free#3]
Can you help me pls Im new to github
Thanks

**Comment by fotvnetwork** [comment]
Good day!
To download, right click on "Raw", then save like as...
You can also paste the link on an IPTV app you are using.

**Comment by marius62810** [comment]
Thanks
--
Sent from myMail for Android joi, 25 iunie 2020, 06:11PM +01:00 from fotvnetwork  notifications@github.com :
