### ISSUE TITLE
Cignal Play Local Channels

### ISSUE THREAD

**Issue by Noyzkie** [fotvnetwork/iptv-free#5]
Hi, request to get local channels from Cignal Play, live streaming local channels.  I do not know how to extract M3u8 files
1. One Sports +
2. One PH
3. One Screen
4. One News
5. Colours
6. TV5
7. One Sports
8. PTV
9. IBC
10. Red by HBO
11. Sari Sari
12. Hits

Thanks

**Comment by fotvnetwork** [comment]
Cignal Play uses DRM-protected links, and can't grab those. Sorry

**Comment by savskii** [comment]
Hey mate i have solution for cignal. can you contact me. Cheers

**Comment by Noyzkie** [comment]
@savskii, how do I contact you? I followed your github

**Comment by savskii** [comment]
Hello send me your skype or telegram

**Comment by Noyzkie** [comment]
@savskii, my telegram is Noyzkie Philippines, thanks

**Comment by savskii** [comment]
Hi mate i cant find u on telegram @Noyzkie

**Comment by 09566771125** [comment]
> Hi, request to get local channels from Cignal Play, live streaming local channels. I do not know how to extract M3u8 files
> 
> 1. One Sports +
> 2. One PH
> 3. One Screen
> 4. One News
> 5. Colours
> 6. TV5
> 7. One Sports
> 8. PTV
> 9. IBC
> 10. Red by HBO
> 11. Sari Sari
> 12. Hits
> 
> Thanks

**Comment by Elesio08** [comment]
@elesio080819 pa send po m3u8 cignal play telegram
