### ISSUE TITLE
Non expiry YouTube live channels

### ISSUE THREAD

**Issue by Noyzkie** [fotvnetwork/iptv-free#9]
Hi Admin, just a suggestion, instead of refreshing youtube address, find the official channel name, this will ensure that your link wont expire.

Thanks for providing IPTV for local Philippines channel, more power to your github

Sample

#EXTINF:22,Kapamilya Online Live (Kodi only)*
plugin://plugin.video.youtube/play/?video_id=Dv4PfCAPJak

#EXTINF:22,Kapamilya Online Live
https://www.youtube.com/abs-cbnentertainment/live

**Comment by fotvnetwork** [comment]
Thanks. I'll try it out.
